x = input()

if x == 0:
    print " * * * "
    print "*     *"
    print "*     *"
    print "*     *"
    print "       "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * \n"
if x == 1:
   # print "       "
    print "      *"
    print "      *"
    print "      *"
    print "       "
    print "      *"
    print "      *"
    print "      *"
    print "       \n" 
if x == 2:
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print " * * * "
    print "*      "
    print "*      "
    print "*      "
    print " * * * \n"
if x == 3:
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print " * * * \n"
if x == 4:
   # print "       "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print "       \n"
if x == 5:
    print " * * * "
    print "*      "
    print "*      "
    print "*      "
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print " * * * \n"
if x == 6:
    print " * * * "
    print "*      "
    print "*      "
    print "*      "
    print " * * * "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * \n"
if x == 7:
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print "       "
    print "      *"
    print "      *"
    print "      *"
    print "       \n"
if x == 8:
    print " * * * "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * \n"
if x == 9:
    print " * * * "
    print "*     *"
    print "*     *"
    print "*     *"
    print " * * * "
    print "      *"
    print "      *"
    print "      *"
    print " * * * \n"